- hosts: all
  tasks:
  - name: Install ntpd
    yum: 
      name: ntp
      state: latest

  - name: Update ntpd conf
    lineinfile:
      path: /etc/ntp.conf
      regexp: "^server 1.centos.pool.ntp.org iburst$"
      line: "server asia.pool.ntp.org iburst"
    notify: restart ntpd

  handlers:
  - name: restart ntpd
    systemd:
      state: restarted
      name: ntpd
