- name: Include RedHat Tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "RedHat"

- name: Include Debian Tasks
  include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"